export const ALL_GEEKS = 'geek_get_all_geeks'
export const DETAILS_GEEK = 'geek_get_details'
export const SAVE_FAV_TEAM = 'geek_save_favorite_team'
export const SAVE_FAV_TEAM_RESET = 'geek_reset_save_favorite_team'
export const DONE = 'geek_all_done'
export const LOADING = 'geek_loading'
export const ERROR = 'geek_error'
export const ERROR_RESET = 'geek_reset_error'