export const ADD_PRONOGEEKS = 'pronogeek_add_pronogeeks'
export const ADD_GEEK_PRONOGEEKS = 'pronogeek_add_other_geek_pronogeeks'
export const SAVING_ALL = 'pronogeek_save_all_matchweek'
export const LOADING = 'pronogeek_loading'
export const ERROR = 'pronogeek_error'