export const ADD_USER_PRONOGEEKS = 'pronogeek_add_pronogeeks'
export const ADD_GEEK_MATCHWEEK_PRONOGEEKS = 'pronogeek_add_other_geek_pronogeeks'
export const ADD_GEEKS_FIXTURE_PRONOGEEKS = 'pronogeek_add_geekleague_fixture_pronogeeks'